apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotify
commonLabels:
  app.kubernetes.io/part-of: gotify
  app.kubernetes.io/instance: gotify

resources:
- gotify.yml
- pvc.yml
- service.yml

secretgenerator:
- name: gotify-config
  type: Opaque