apiVersion: v1
kind: Service
metadata:
  labels: &gotify_labels
    app.kubernetes.io/part-of: gotify
    app.kubernetes.io/instance: gotify
  name: gotify-admin
spec:
  selector: *gotify_labels
  ports:
  - port: 8080  
    name: gotify-admin